# Schema for the configuration files of the Nature theme.

nature.settings:
  type: theme_settings
  label: 'Nature settings'
  mapping:
    site_branding_bg_color:
      type: string
      label: 'Site branding background color'
