<?php

/**
 * Implements hook_preprocess_region().
 */
function nature_preprocess_region(&$variables) {
  if ($variables['region'] == 'header') {
    $variables['attributes']['class'][] = theme_get_setting('site_branding_bg_color');
  }
}

/**
 * Implements hook_preprocess_HOOK() for HTML titles.
 */
function nature_preprocess_html(&$variables) {
  // Example: Add an icon to the title
  $variables['head_title'] = '<i class="fas fa-leaf"></i> ' . $variables['head_title'];
}
